### ISSUE TITLE
README :: Create the indexes :: Wrong path to reindex.py

### ISSUE THREAD

**Issue by AlesCUMSI** [EGA-archive/beacon-production-prototype#3]
I guess it's a copy-paste error.

Current text:
docker exec beacon python beacon/reindex.py

Corrected text:
docker exec beaconprod python /beacon/connections/mongo/reindex.py

**Comment by costero-e** [comment]
HI @AlesCUMSI , thank you very much for reporting this! I just ammended this in the last commit #ac31fd31105ea1469195e14c1400118f1e5fe831. 
Best,
Oriol
